name: Deploy Website

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_DEPLOY_TOKEN }}

    # (Optional) Build step if you have a build process
    # - name: Build site
    #   run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        
        # Example: Push content from your built folder (e.g., ./dist) to gh-pages branch
        git add .
        git commit -m "Deploy website"
        git push origin HEAD:gh-pages --force
